# Generated by Django 3.2.6 on 2022-05-26 04:19

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('user_type', models.CharField(choices=[('Guest', 'Guest'), ('Player', 'Player')], max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('phone_no', models.PositiveIntegerField(verbose_name='Phone Number')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='player/image')),
                ('level', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.PositiveIntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Accounts',
                'ordering': ('username',),
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='partners/photo')),
            ],
            options={
                'verbose_name_plural': 'Partners',
            },
        ),
        migrations.CreateModel(
            name='PlayerParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.PositiveIntegerField()),
                ('photo', models.ImageField(upload_to='playerparticipation/photo')),
                ('level', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('zip_status', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'PlayerParticipations',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='sponsors/photo')),
            ],
            options={
                'verbose_name_plural': 'Sponsors',
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_photo', models.ImageField(upload_to='banner/photo')),
                ('tournament_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='tournament_names')),
                ('start_date', models.DateField()),
                ('participation_deadline', models.DateField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('participation_fee', models.PositiveIntegerField()),
                ('gym_name', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.PositiveIntegerField()),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament', to='accounts.partner')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='accounts.sponsor')),
            ],
            options={
                'verbose_name_plural': 'Tournaments',
            },
        ),
    ]
